In [1]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
X, y = load_iris(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=104, test_size=0.25, shuffle=True)

In [8]:
import numpy as np
class KNN:
  def __init__(self, K) -> None:
    self.n_neighbors = K

  def findDistance(self, array1, array2):
    # Finding Euclidean Distance
    point1 = np.array(array1)
    point2 = np.array(array2)

    dist = np.linalg.norm(point1 - point2)
    return dist

  def minValueIndex(self, array):
    x = np.array(array)
    res = np.argmin(x)
    array[res] = float('inf')
    return res

  def predict(self, unknown, dataset, knownClasses):
    distanceArray = []
    for i in range(len(dataset)):
      distanceArray.append(self.findDistance(unknown, dataset[i]))

    closestDisInd = []
    for i in range(self.n_neighbors):
      closestDisInd.append(self.minValueIndex(distanceArray))

    res = {}
    for i in closestDisInd:
      if knownClasses[i] not in res:
        res[knownClasses[i]] = 1
      else:
        res[knownClasses[i]] += 1
    print(res)

    myKeys = list(res.keys())
    mx = max(myKeys)
    return mx

In [9]:
knn = KNN(5)
predicted = []
for i in X_test:
  #knn.predict(X[100], X, y)
  predicted.append(knn.predict(i, X_train, y_train))
print(predicted)

{0: 5}
{0: 5}
{0: 5}
{1: 5}
{2: 4, 1: 1}
{1: 2, 2: 3}
{1: 5}
{2: 5}
{1: 5}
{0: 5}
{0: 5}
{1: 5}
{1: 5}
{2: 5}
{1: 5}
{0: 5}
{1: 5}
{1: 5}
{2: 5}
{0: 5}
{1: 5}
{0: 5}
{2: 5}
{0: 5}
{2: 5}
{1: 5}
{0: 5}
{0: 5}
{0: 5}
{1: 5}
{0: 5}
{0: 5}
{2: 4, 1: 1}
{0: 5}
{2: 5}
{1: 5}
{1: 5}
{0: 5}
[0, 0, 0, 1, 2, 2, 1, 2, 1, 0, 0, 1, 1, 2, 1, 0, 1, 1, 2, 0, 1, 0, 2, 0, 2, 1, 0, 0, 0, 1, 0, 0, 2, 0, 2, 1, 1, 0]


In [10]:
from sklearn.metrics import precision_recall_fscore_support as score
precision, recall, fscore, support = score(y_test, predicted)
print(precision, recall, fscore, support, sep="\n")

[1.         1.         0.88888889]
[1.         0.92857143 1.        ]
[1.         0.96296296 0.94117647]
[16 14  8]
